[profile.default]
src = 'contracts/src'
test = 'contracts/test'
out = 'contracts/out'
libs = ['contracts/lib']
solc = '0.8.9'
optimizer_runs = 10_000

[rpc_endpoints]
scroll='https://alpha-rpc.scroll.io/l2'
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[etherscan]
534353= { key = "${ETHERSCAN_API_KEY}" }
84531= { key = "${ETHERSCAN_API_KEY}" }