[profile.default]
src = 'contracts/src'
test = 'contracts/test'
out = 'contracts/out'
libs = ['contracts/lib']
solc = '0.8.9'
optimizer_runs = 10_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config